cat > ~/projeto-qoe/streaming/nginx.conf << 'EOF'
server {
    listen 80;
    server_name localhost;

    root /home/sam/projeto-qoe/streaming/dash;
    index stream.mpd;

    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control no-cache;

        types {
            application/dash+xml mpd;
            video/mp4 m4s mp4;
        }
    }
}
EOF